# Generated by Django 3.0.8 on 2020-07-08 13:14

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("form_id", models.IntegerField(null=True)),
                ("material", models.TextField(blank=True, null=True)),
                ("video", models.TextField(blank=True, null=True)),
                ("slideshare", models.TextField(blank=True, null=True)),
                (
                    "data",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criteria",
                    models.CharField(
                        choices=[
                            ("access", "Access"),
                            ("quality", "Quality"),
                            ("visual rep", "Visual representation"),
                            ("engagement", "Engagement"),
                            ("inclussion", "Inclussion"),
                            ("licensing", "Licensing"),
                            ("accessibility", "Accessibility"),
                            ("currency", "Currency"),
                            ("assessment", "Assessment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("score", models.IntegerField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.Entry"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoginKey",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("key", models.CharField(max_length=32)),
                ("used", models.BooleanField(default=False)),
                ("pub_date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
