# Generated by Django 3.0.8 on 2020-07-13 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entry", old_name="form_id", new_name="entry_id",
        ),
    ]
