# Generated by Django 3.0.8 on 2020-07-13 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_auto_20200713_0953"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Individual Awards", "Individual Awards"),
                            ("Open Assets Awards", "Open Assets Awards"),
                            ("Open Practices Awards", "Open Practices Awards"),
                            ("Special Awards", "Special Awards"),
                        ],
                        max_length=120,
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="entry",
            options={"verbose_name": "Entry", "verbose_name_plural": "Entries"},
        ),
        migrations.AddField(
            model_name="entry",
            name="subcategory",
            field=models.CharField(blank=True, max_length=125),
        ),
        migrations.AddField(
            model_name="entry",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="web.Category",
            ),
        ),
    ]
