# Generated by Django 3.0.8 on 2020-07-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_auto_20200713_1603"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.RemoveField(model_name="rating", name="criteria",),
        migrations.RemoveField(model_name="rating", name="score",),
        migrations.AddField(
            model_name="rating",
            name="access",
            field=models.IntegerField(null=True, verbose_name="Access"),
        ),
        migrations.AddField(
            model_name="rating",
            name="accessibility",
            field=models.IntegerField(null=True, verbose_name="Accessibility"),
        ),
        migrations.AddField(
            model_name="rating",
            name="assessment",
            field=models.IntegerField(null=True, verbose_name="Assessment"),
        ),
        migrations.AddField(
            model_name="rating",
            name="currency",
            field=models.IntegerField(null=True, verbose_name="Currency"),
        ),
        migrations.AddField(
            model_name="rating",
            name="engagement",
            field=models.IntegerField(null=True, verbose_name="Engagement"),
        ),
        migrations.AddField(
            model_name="rating",
            name="inclussion",
            field=models.IntegerField(null=True, verbose_name="Inclussion"),
        ),
        migrations.AddField(
            model_name="rating",
            name="licensing",
            field=models.IntegerField(null=True, verbose_name="Licensing"),
        ),
        migrations.AddField(
            model_name="rating",
            name="quality",
            field=models.IntegerField(null=True, verbose_name="Quality"),
        ),
        migrations.AddField(
            model_name="rating",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft rating"),
                    (
                        "conflict",
                        "Conflict of interest or can't understand the language",
                    ),
                    ("done", "Completed rating"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="rating",
            name="visual",
            field=models.IntegerField(null=True, verbose_name="Visual representation"),
        ),
        migrations.AlterField(
            model_name="category", name="name", field=models.CharField(max_length=120),
        ),
    ]
