# Generated by Django 3.0.8 on 2020-07-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_auto_20200714_1013"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
