# Generated by Django 3.0.8 on 2020-07-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_rating_updated"),
    ]

    operations = [
        migrations.RemoveField(model_name="rating", name="inclussion",),
        migrations.AddField(
            model_name="rating",
            name="inclusion",
            field=models.IntegerField(
                help_text="Promotes inclusiveness and diversity through the use of variety of languages.",
                null=True,
                verbose_name="Inclusion",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="access",
            field=models.IntegerField(
                help_text="Resources are easily accesible and readily available to anyone.",
                null=True,
                verbose_name="Access",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="accessibility",
            field=models.IntegerField(
                help_text="The resource supports learners with diverse needs.",
                null=True,
                verbose_name="Accessibility",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="assessment",
            field=models.IntegerField(
                help_text="A form of certification or accreditaiton is available.",
                null=True,
                verbose_name="Assessment",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="currency",
            field=models.IntegerField(
                help_text="Information is current and updated.  Date of materiales is clearly indicated.",
                null=True,
                verbose_name="Currency",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="engagement",
            field=models.IntegerField(
                help_text="Provides multiple means of engagement through social learning connections, networks and/or communities.",
                null=True,
                verbose_name="Engagement",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="licensing",
            field=models.IntegerField(
                help_text="Copyright and Fair Use guidelines are followed with proper use of citations.  An open license is clearly stated.",
                null=True,
                verbose_name="Licensing",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="quality",
            field=models.IntegerField(
                help_text="Exemplary quality in the presentation of content (in breadth, depth, creativity)",
                null=True,
                verbose_name="Quality",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="visual",
            field=models.IntegerField(
                help_text="Uses multiple means of visual representation through accessible embedded multimedia content.",
                null=True,
                verbose_name="Visual representation",
            ),
        ),
    ]
