# Generated by Django 3.0.8 on 2020-07-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0006_auto_20200716_1236"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating", name="comment", field=models.TextField(blank=True),
        ),
    ]
