# Generated by Django 3.0.8 on 2020-07-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0008_auto_20200730_1256"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="individual",
            field=models.IntegerField(null=True, verbose_name="Individual Rating"),
        ),
    ]
